/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz_Grafica;

import Interfaz_Mensajes.InterfaceMensajes;
import Logica.logica_Articulo;
import Objetos.Articulo;
import Objetos.Imprimir;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Randall
 */
public class Ventana_Articulo extends javax.swing.JFrame {

    Imprimir imprimir = new Imprimir();
    Articulo articuloDevuelto = new Articulo();
    InterfaceMensajes interfmesj = new InterfaceMensajes();
    logica_Articulo logica = new logica_Articulo();

    /**
     * Constructor de la ventana, inicializa componentes.
     */
    public Ventana_Articulo() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/art.jpg"));
        setIconImage(icon);
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_Upc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Categoria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Costo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        txt_Impuesto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Cantidad = new javax.swing.JTextField();
        txt_Localizacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_Descripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Proveedor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_Precio = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        txt_Impuesto2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jcb_Descripcion = new javax.swing.JCheckBox();
        txt_Alterna = new javax.swing.JTextField();
        jcb_Serie = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_Serie = new javax.swing.JTextField();
        txt_Reordenamiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_Nuevo = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Imprimir = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("UPC/EAN/ISBN:");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Categoría:");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Costo:");

        txt_Costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CostoKeyTyped(evt);
            }
        });

        jLabel7.setText("Impuesto 1:");

        jTextField4.setEditable(false);
        jTextField4.setText("IGV");

        txt_Impuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ImpuestoKeyTyped(evt);
            }
        });

        jLabel21.setText("%");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Cantidad:");

        txt_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CantidadKeyTyped(evt);
            }
        });

        jLabel9.setText("Localización:");

        jLabel10.setText("Descripción:");

        txa_Descripcion.setColumns(20);
        txa_Descripcion.setRows(5);
        jScrollPane1.setViewportView(txa_Descripcion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(40, 40, 40)
                            .addComponent(txt_Upc, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(64, 64, 64)
                            .addComponent(txt_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(83, 83, 83)
                            .addComponent(txt_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(57, 57, 57)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(55, 55, 55)
                            .addComponent(txt_Localizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(51, 51, 51)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_Upc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel4)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel5)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(txt_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel7)))
                    .addGap(43, 43, 43)
                    .addComponent(jLabel8)
                    .addGap(28, 28, 28)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel9))
                        .addComponent(txt_Localizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel10))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Nombre del Artículo:");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Proveedor:");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Precio Unitario:");

        txt_Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PrecioKeyTyped(evt);
            }
        });

        jTextField12.setEditable(false);
        jTextField12.setText("Percepción IGV");
        jTextField12.setToolTipText("");

        txt_Impuesto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Impuesto2KeyTyped(evt);
            }
        });

        jLabel22.setText("%");

        jLabel14.setText("Impuesto 2");

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Nivel de");

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Reordenamiento:");

        jLabel16.setText("Permitir Descripción");

        jLabel18.setText("Alterna:");

        jcb_Descripcion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcb_DescripcionStateChanged(evt);
            }
        });

        txt_Alterna.setEnabled(false);
        txt_Alterna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_AlternaMouseClicked(evt);
            }
        });

        jcb_Serie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_SerieItemStateChanged(evt);
            }
        });

        jLabel19.setText("El Artículo tiene");

        jLabel20.setText("Número de Serie:");

        txt_Serie.setEnabled(false);
        txt_Serie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_SerieMouseClicked(evt);
            }
        });

        txt_Reordenamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ReordenamientoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(71, 71, 71)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(txt_Impuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Reordenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_Descripcion)
                            .addComponent(txt_Alterna, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_Serie)
                                    .addComponent(txt_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(txt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14)))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Impuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_Reordenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel18)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel19)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jcb_Descripcion)
                        .addGap(9, 9, 9)
                        .addComponent(txt_Alterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jcb_Serie)
                        .addGap(2, 2, 2)
                        .addComponent(txt_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        if (jcb_Descripcion.isSelected() == true){
            txt_Alterna.enable();
        }

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 43, 341, -1));

        jLabel3.setText("Los campos en rojo son requeridos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 11, -1, -1));

        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 460, 80, -1));

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 489, -1, -1));

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 489, 80, -1));

        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 80, -1));

        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.jpg"))); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 458, 110, -1));

        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.jpg"))); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 488, 110, -1));

        btn_Imprimir.setText("Imprimir");
        btn_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));

        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 738, 520));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Actualizar Artículo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 758, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que valida que no se ingresen letras en campos designados para
     * números.
     *
     */
    private void txt_ImpuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ImpuestoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
            interfmesj.mostrarMensajeAdvertencia("Ingresa Solo Numeros");
        }
    }//GEN-LAST:event_txt_ImpuestoKeyTyped

    /**
     * Método que valida que no se ingresen letras en campos designados para
     * números.
     *
     */
    private void txt_Impuesto2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Impuesto2KeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
            interfmesj.mostrarMensajeAdvertencia("Ingresa Solo Numeros");
        }
    }//GEN-LAST:event_txt_Impuesto2KeyTyped

    /**
     * Método que valida la habilitacion de un campo de texto.
     *
     */
    private void jcb_DescripcionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcb_DescripcionStateChanged
        if (jcb_Descripcion.isSelected() == true) {
            txt_Alterna.enable();
        } else {
            txt_Alterna.setText("");
            txt_Alterna.disable();

        }
    }//GEN-LAST:event_jcb_DescripcionStateChanged

    /**
     * Método que avisa que se debe seleccionar primero otra opcion.
     *
     */
    private void txt_AlternaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_AlternaMouseClicked
        if (jcb_Descripcion.isSelected() == false) {
            interfmesj.mostrarMensajeAdvertencia(" Primero seleccione el check de arriba");
        }
    }//GEN-LAST:event_txt_AlternaMouseClicked

    /**
     * Método que valida la habilitacion de un campo de texto.
     *
     */
    private void jcb_SerieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_SerieItemStateChanged
        if (jcb_Serie.isSelected() == true) {
            txt_Serie.enable();
        } else {
            txt_Serie.setText("");
            txt_Serie.disable();

        }
    }//GEN-LAST:event_jcb_SerieItemStateChanged

    /**
     * Método que valida el cierre deuna ventana y no de todo el sistema.
     *
     */
    private void btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoActionPerformed
        Ventana_Articulo ventana = new Ventana_Articulo();
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);
    }//GEN-LAST:event_btn_NuevoActionPerformed

    /**
     * Método que guarda en la base de datos un nuevo articulo.
     *
     */
    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        if (txt_Categoria.getText().trim().equals("") || txt_Costo.getText().trim().equals("") || txt_Cantidad.getText().trim().equals("") || txt_Nombre.getText().trim().equals("") || txt_Proveedor.getText().trim().equals("") || txt_Precio.getText().trim().equals("") || txt_Reordenamiento.getText().trim().equals("")) {

            interfmesj.mostrarMensajeError("Ingrese todos los datos que se solicitan como obligatorios  \n están en color rojo.");
        } else {
            Articulo articulo = new Articulo();
            articulo.setUpceanisbn(txt_Upc.getText());
            articulo.setCategoria(txt_Categoria.getText());
            articulo.setCosto(Double.parseDouble(txt_Costo.getText()));
            if (!txt_Impuesto.getText().equals("")) {
                articulo.setImpuesto_1(Float.parseFloat(txt_Impuesto.getText()));
            }
            articulo.setCantidad(Integer.parseInt(txt_Cantidad.getText()));
            articulo.setLocalizacion(txt_Localizacion.getText());
            articulo.setDescripcion(txa_Descripcion.getText());
            articulo.setNombre(txt_Nombre.getText());
            articulo.setProveedor(txt_Proveedor.getText());
            articulo.setPrecio_unitario(Double.parseDouble(txt_Precio.getText()));
            if (!txt_Impuesto2.getText().equals("")) {
                articulo.setImpuesto_2(Float.parseFloat(txt_Impuesto2.getText()));
            }
            articulo.setReordenamiento(Integer.parseInt(txt_Reordenamiento.getText()));
            articulo.setDescripcion_alterna(txt_Alterna.getText());
            articulo.setNumero_serie(txt_Serie.getText());
            logica.insertarArticulo(articulo);

        }
    }//GEN-LAST:event_btn_GuardarActionPerformed

    /**
     * Método que cierra el sistema.
     *
     */
    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_CerrarActionPerformed

    /**
     * Método que avisa que se debe seleccionar primero otra opcion.
     *
     */
    private void txt_SerieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_SerieMouseClicked
        if (jcb_Serie.isSelected() == false) {
            interfmesj.mostrarMensajeAdvertencia(" Primero seleccione el check de arriba");
        }
    }//GEN-LAST:event_txt_SerieMouseClicked

    /**
     * Método que busca en la base de datos un articulo.
     *
     */
    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        if (!txt_Categoria.getText().trim().equals("") && !txt_Nombre.getText().trim().equals("")) {
            Articulo articulo = new Articulo();
            articulo.setCategoria(txt_Categoria.getText());
            articulo.setNombre(txt_Nombre.getText());
            articuloDevuelto = logica.buscarArticulo(articulo);
            boolean seguir = logica.continuar();
            if (seguir) {
                txt_Upc.setText(articuloDevuelto.getUpceanisbn());
                txt_Costo.setText("" + articuloDevuelto.getCosto());
                txt_Impuesto.setText("" + articuloDevuelto.getImpuesto_1());
                txt_Cantidad.setText("" + articuloDevuelto.getCantidad());
                txt_Localizacion.setText(articuloDevuelto.getLocalizacion());
                txa_Descripcion.setText(articuloDevuelto.getDescripcion());
                txt_Proveedor.setText(articuloDevuelto.getProveedor());
                txt_Precio.setText("" + articuloDevuelto.getPrecio_unitario());
                txt_Impuesto2.setText("" + articuloDevuelto.getImpuesto_2());
                txt_Reordenamiento.setText("" + articuloDevuelto.getReordenamiento());
                txt_Alterna.setText(articuloDevuelto.getDescripcion_alterna());
                txt_Serie.setText(articuloDevuelto.getNumero_serie());
                if (articuloDevuelto.getDescripcion_alterna() != null) {
                    jcb_Descripcion.setSelected(true);
                } else {
                    jcb_Descripcion.setSelected(false);
                }
                if (articuloDevuelto.getNumero_serie() != null) {
                    jcb_Serie.setSelected(true);
                } else {
                    jcb_Serie.setSelected(false);
                }
            }
        } else {
            interfmesj.mostrarMensajeAdvertencia(" La búsqueda se realizará, con los campos de nombre y categoría, \n Por favor asegúrese de llenar ambos campos");
        }

    }//GEN-LAST:event_btn_BuscarActionPerformed

    /**
     * Método que valida que no se ingresen letras en campos designados para
     * números.
     *
     */
    private void txt_CostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CostoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
            interfmesj.mostrarMensajeAdvertencia("Ingresa Solo Numeros");
        }
    }//GEN-LAST:event_txt_CostoKeyTyped

    /**
     * Método que valida que no se ingresen letras en campos designados para
     * números.
     *
     */
    private void txt_CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CantidadKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
            interfmesj.mostrarMensajeAdvertencia("Ingresa Solo Numeros");
        }
    }//GEN-LAST:event_txt_CantidadKeyTyped

    /**
     * Método que valida que no se ingresen letras en campos designados para
     * números.
     *
     */
    private void txt_PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PrecioKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
            interfmesj.mostrarMensajeAdvertencia("Ingresa Solo Numeros");
        }
    }//GEN-LAST:event_txt_PrecioKeyTyped

    /**
     * Método que valida que no se ingresen letras en campos designados para
     * números.
     *
     */
    private void txt_ReordenamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ReordenamientoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
            interfmesj.mostrarMensajeAdvertencia("Ingresa Solo Numeros");
        }
    }//GEN-LAST:event_txt_ReordenamientoKeyTyped

    /**
     * Método encargado de editar un artículo.
     *
     */
    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        if (txt_Categoria.getText().trim().equals("") || txt_Costo.getText().trim().equals("") || txt_Cantidad.getText().trim().equals("") || txt_Nombre.getText().trim().equals("") || txt_Proveedor.getText().trim().equals("") || txt_Precio.getText().trim().equals("") || txt_Reordenamiento.getText().trim().equals("")) {
            interfmesj.mostrarMensajeError("Ingrese todos los datos que se solicitan como obligatorios  \n están en color rojo.");
        } else {
            if (articuloDevuelto.getID() != 0) {
                Articulo articulo = new Articulo();
                articulo.setUpceanisbn(txt_Upc.getText());
                articulo.setCategoria(txt_Categoria.getText());
                articulo.setCosto(Double.parseDouble(txt_Costo.getText()));
                if (!txt_Impuesto.getText().equals("")) {
                    articulo.setImpuesto_1(Float.parseFloat(txt_Impuesto.getText()));
                }
                articulo.setCantidad(Integer.parseInt(txt_Cantidad.getText()));
                articulo.setLocalizacion(txt_Localizacion.getText());
                articulo.setDescripcion(txa_Descripcion.getText());
                articulo.setNombre(txt_Nombre.getText());
                articulo.setProveedor(txt_Proveedor.getText());
                articulo.setPrecio_unitario(Double.parseDouble(txt_Precio.getText()));
                if (!txt_Impuesto2.getText().equals("")) {
                    articulo.setImpuesto_2(Float.parseFloat(txt_Impuesto2.getText()));
                }
                articulo.setReordenamiento(Integer.parseInt(txt_Reordenamiento.getText()));
                articulo.setDescripcion_alterna(txt_Alterna.getText());
                articulo.setNumero_serie(txt_Serie.getText());
                int id = 0;
                id = articuloDevuelto.getID();
                logica.modificarArticulo(id, articulo);
            } else {
                interfmesj.mostrarMensajeAdvertencia("Primero debe buscar el artículo a Editar");
            }
        }
    }//GEN-LAST:event_btn_EditarActionPerformed

    /**
     * Método que retorna a los valores predeterminados del sistema.
     *
     */
    public void camposenblanco() {
        txt_Upc.setText("");
        txt_Categoria.setText("");
        txt_Costo.setText("");
        txt_Impuesto.setText("");
        txt_Cantidad.setText("");
        txt_Localizacion.setText("");
        txa_Descripcion.setText("");
        txt_Nombre.setText("");
        txt_Proveedor.setText("");
        txt_Precio.setText("");
        txt_Impuesto2.setText("");
        txt_Reordenamiento.setText("");
        txt_Alterna.setText("");
        txt_Serie.setText("");
        jcb_Descripcion.setSelected(false);
        jcb_Serie.setSelected(false);
        articuloDevuelto.setID(0);
    }

    /**
     * Método que elimina un artículo de la base de datos.
     *
     */
    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        if (articuloDevuelto.getID() != 0) {
            int id = 0;
            id = articuloDevuelto.getID();
            logica.eliminarArticulo(id);
            camposenblanco();
        } else {
            interfmesj.mostrarMensajeAdvertencia("Primero debe buscar el artículo a Eliminar");
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    /**
     * Método que retorna a los valores predeterminados del sistema.
     *
     */
    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        camposenblanco();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    /**
     * Método que imprime en pdf un articulo.
     *
     */
    private void btn_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirActionPerformed
        if (articuloDevuelto.getID() != 0) {
            StringBuilder texto = new StringBuilder();
            String upceanisbn = articuloDevuelto.getUpceanisbn();
            String categoria = articuloDevuelto.getCategoria();
            String costo = "" + articuloDevuelto.getCosto();
            String impuesto1 = "" + articuloDevuelto.getImpuesto_1();
            String cantidad = "" + articuloDevuelto.getCantidad();
            String localizacion = articuloDevuelto.getLocalizacion();
            String descripcion = articuloDevuelto.getDescripcion();
            String nombre = articuloDevuelto.getNombre();
            String proveedor = articuloDevuelto.getProveedor();
            String precio = "" + articuloDevuelto.getPrecio_unitario();
            String impuesto2 = "" + articuloDevuelto.getImpuesto_2();
            String reordenamiento = "" + articuloDevuelto.getReordenamiento();
            String descripcionalterna = articuloDevuelto.getDescripcion_alterna();
            String numeroserie = articuloDevuelto.getNumero_serie();
            if (upceanisbn == null) {
                upceanisbn = "No tiene dato ingresado";
            }
            if (impuesto1 == null) {
                impuesto1 = "No tiene dato ingresado";
            }
            if (localizacion == null) {
                localizacion = "No tiene dato ingresado";
            }
            if (descripcion == null) {
                descripcion = "No tiene dato ingresado";
            }
            if (impuesto2 == null) {
                impuesto2 = "No tiene dato ingresado";
            }
            if (descripcionalterna == null) {
                descripcionalterna = "No tiene dato ingresado";
            }
            if (numeroserie == null) {
                numeroserie = "No tiene dato ingresado";
            }
            texto.append("Articulo  \n" + "UPC/EAN/ISBN: " + upceanisbn + "\n Categoría: " + categoria + "\n Costo: " + costo + "\n Impuesto 1: " + impuesto1 + "\n Cantidad: " + cantidad + "\n Localización: " + localizacion + "\n Descripción: " + descripcion + "\n Nombre del Artículo: " + nombre + "\n Proveedor: " + proveedor + "\n Precio Unitario: " + precio + "\n Impuesto 2: " + impuesto2 + "\n Nivel de Reordenamiento: " + reordenamiento + "\n Descripción Alterna: " + descripcionalterna + "\n Número de Serie: " + numeroserie);
            if (texto.length() != 0) {
                imprimir.convertirPDF(texto);
                interfmesj.mostrarMensajeExito("La impresion PDF a sido creada \n.");
            }
        } else {
            interfmesj.mostrarMensajeAdvertencia("Primero debe buscar el artículo antes de imprimirlo");
        }
    }//GEN-LAST:event_btn_ImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Imprimir;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JCheckBox jcb_Descripcion;
    private javax.swing.JCheckBox jcb_Serie;
    private javax.swing.JTextArea txa_Descripcion;
    private javax.swing.JTextField txt_Alterna;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Categoria;
    private javax.swing.JTextField txt_Costo;
    private javax.swing.JTextField txt_Impuesto;
    private javax.swing.JTextField txt_Impuesto2;
    private javax.swing.JTextField txt_Localizacion;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Precio;
    private javax.swing.JTextField txt_Proveedor;
    private javax.swing.JTextField txt_Reordenamiento;
    private javax.swing.JTextField txt_Serie;
    private javax.swing.JTextField txt_Upc;
    // End of variables declaration//GEN-END:variables
}//Fin de la clase.
